// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file commonIdlInfo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _COMMONIDLINFO_H_
#define _COMMONIDLINFO_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(commonIdlInfo_SOURCE)
#define commonIdlInfo_DllAPI __declspec( dllexport )
#else
#define commonIdlInfo_DllAPI __declspec( dllimport )
#endif // commonIdlInfo_SOURCE
#else
#define commonIdlInfo_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define commonIdlInfo_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace tg_msgs {
    namespace dds {
        /*!
         * @brief This class represents the enumeration BoxType defined by the user in the IDL file.
         * @ingroup COMMONIDLINFO
         */
        enum BoxType : uint32_t
        {
            ENUM_RESERVE,
            ENUM_MASTER_BOX,
            ENUM_SLAVE_BOX
        };
        /*!
         * @brief This class represents the enumeration LinkStatus defined by the user in the IDL file.
         * @ingroup COMMONIDLINFO
         */
        enum LinkStatus : uint32_t
        {
            ENUM_CONNECT,
            ENUM_DISCONNECT
        };
        /*!
         * @brief This class represents the enumeration moudleType defined by the user in the IDL file.
         * @ingroup COMMONIDLINFO
         */
        enum moudleType : uint32_t
        {
            UnknownModule,
            CCU,
            CGU,
            CGU_TBOX,
            HMI,
            ICU
        };
    } // namespace dds
} // namespace tg_msgs

#endif // _COMMONIDLINFO_H_