// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file commonIdlInfoTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _COMMONIDLINFO_TYPE_OBJECT_H_
#define _COMMONIDLINFO_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(commonIdlInfo_SOURCE)
#define commonIdlInfo_DllAPI __declspec( dllexport )
#else
#define commonIdlInfo_DllAPI __declspec( dllimport )
#endif // commonIdlInfo_SOURCE
#else
#define commonIdlInfo_DllAPI
#endif
#else
#define commonIdlInfo_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registercommonIdlInfoTypes();

eProsima_user_DllExport const TypeIdentifier* GetBoxTypeIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetBoxTypeObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalBoxTypeObject();
eProsima_user_DllExport const TypeObject* GetCompleteBoxTypeObject();

eProsima_user_DllExport const TypeIdentifier* GetLinkStatusIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetLinkStatusObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalLinkStatusObject();
eProsima_user_DllExport const TypeObject* GetCompleteLinkStatusObject();

eProsima_user_DllExport const TypeIdentifier* GetmoudleTypeIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetmoudleTypeObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalmoudleTypeObject();
eProsima_user_DllExport const TypeObject* GetCompletemoudleTypeObject();


#endif // _COMMONIDLINFO_TYPE_OBJECT_H_