#ifndef SSLCONFIGPLUGIN_GLOBAL_H
#define SSLCONFIGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SSLCONFIGPLUGIN_LIBRARY)
#  define SSLCONFIGPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SSLCONFIGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SSLCONFIGPLUGIN_GLOBAL_H
