// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file systemInfoTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _TG_MSGS_DDS_SYSTEMINFO_TYPE_OBJECT_H_
#define _TG_MSGS_DDS_SYSTEMINFO_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(systemInfo_SOURCE)
#define systemInfo_DllAPI __declspec( dllexport )
#else
#define systemInfo_DllAPI __declspec( dllimport )
#endif // systemInfo_SOURCE
#else
#define systemInfo_DllAPI
#endif
#else
#define systemInfo_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registersystemInfoTypes();

eProsima_user_DllExport const TypeIdentifier* GetmoudleTypeIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetmoudleTypeObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalmoudleTypeObject();
eProsima_user_DllExport const TypeObject* GetCompletemoudleTypeObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgDiskStatSTIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgDiskStatSTObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgDiskStatSTObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgDiskStatSTObject();

eProsima_user_DllExport const TypeIdentifier* GetMsgDiskMonitorIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgDiskMonitorObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgDiskMonitorObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgDiskMonitorObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgProcessSTIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgProcessSTObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgProcessSTObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgProcessSTObject();

eProsima_user_DllExport const TypeIdentifier* GetMsgCPUMEMMonitorIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgCPUMEMMonitorObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgCPUMEMMonitorObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgCPUMEMMonitorObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgKILLProcessIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgKILLProcessObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgKILLProcessObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgKILLProcessObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgClearAllIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgClearAllObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgClearAllObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgClearAllObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgShellCMDIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgShellCMDObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgShellCMDObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgShellCMDObject();


eProsima_user_DllExport const TypeIdentifier* GetMsgShellCMDResultIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMsgShellCMDResultObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMsgShellCMDResultObject();
eProsima_user_DllExport const TypeObject* GetCompleteMsgShellCMDResultObject();


#endif // _TG_MSGS_DDS_SYSTEMINFO_TYPE_OBJECT_H_