#ifndef DATAINTERFACEHMI_GLOBAL_H
#define DATAINTERFACEHMI_GLOBAL_H

#include <QtCore/qglobal.h>
#include <iostream>

#if defined(DATAINTERFACEHMI_LIBRARY)
#  define DATAINTERFACEHMI_EXPORT Q_DECL_EXPORT
#else
#  define DATAINTERFACEHMI_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAINTERFACEHMI_GLOBAL_H
