#ifndef SYSTEMINFOPLUGIN_GLOBAL_H
#define SYSTEMINFOPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSTEMINFOPLUGIN_LIBRARY)
#  define SYSTEMINFOPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SYSTEMINFOPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSTEMINFOPLUGIN_GLOBAL_H
